  <main class="main container bg-primary">
    <div class="main_wrapper container pb-3 venta-bg">
      <div class="container">
        <h1 class="text-center">The Elder Scrolls V of Skyrim</h1>
        <div class="textBox text-justify">
          <h2 class="font-weight-bold text-primary text-center">2011-2020</h2>
          <p>In the first few years of this new decade three trophies were added to the cabinet by José Mourinho's Real Madrid. The most notable was the 2011-12 Liga title, which they won with a record-breaking 100 points, the highest score achieved in the history of the championship at that stage, and 121 goals. They also beat Barcelona to clinch a Copa del Rey and a Supercopa de España.</p>
          <p>In June 2013, Carlo Ancelotti arrived at Real Madrid. The Italian won four trophies with the Whites, the first coming in the shape of Real Madrid's nineteenth Copa del Rey, after beating Barcelona 1-2 in the final. On 24 May 2014, Madrid lifted the European Cup once again, claiming La Décima with a 4-1 victory over Atlético in Lisbon. Goals from Ramos, Bale, Marcelo and Cristiano secured the triumph</p>
          <p>Two further triumphs arrived in the second season under Ancelotti: The European Super Cup, against Sevilla and Real Madrid’s first World Club Cup, against San Lorenzo. This meant Real Madrid capped of a historic year in their history in 2014, making it the year in which most trophies were won by the club. In June 2015, Rafa Benítez returned to the club where he cut his teeth, to take charge of the Whites. Then, in January 2016, Zidane made the step up to first team coach, following his legendary career as a player. His first season ended with the team lifting the La Undécima trophy, against Atlético in Milán.</p>
          <p>The French tactician's second season in charge delivered a clutch of silverware. Real Madrid secured the Duodécima, becoming the first-ever team to successfully defend their continental crown in the Champions League era. Alongside this success in Europe's elite club competition, the team also captured the 2016/17 LaLiga crown, the club's third UEFA Super Cup and a second Club World Cup, after overcoming Manchester United, as well as a 10th Spanish Super Cup. In December 2017, the Whites clinched another Club World Cup crown and this fifth piece of silverware saw the team set a new record for the number of titles claimed in a calendar year. 2018 is also a big part of the Real Madrid legend thanks to la Decimotercera, won against Liverpool the final played in Kiev, as well as being crowned world champions for the seventh time after beating Al Ain in the United Arab Emirates.</p>
          <hr>
          <h2 class="font-weight-bold text-primary text-center">Stadium Santiago Bernabéu</h2>

          <img src="<?php echo base_url() ?>/assets/img/body.jpg" class="img-thumbnail bg-primary" alt="">
          <h2 class="font-weight-bold text-primary text-center">2001-2010</h2>
          <p>Vicente del Bosque stayed on as manager until 2003. His philosophy and brand of football made Madrid into a team of champions. During his time at the helm, the Whites celebrated another European Cup victory, another Intercontinental Cup, two domestic championships, a Supercup of Spain and a UEFA Super Cup. It was an era that is only comparable with the Real Madrid of the 50s and 60s.</p>
          <p> 
          Florentino Pérez's management led to profound changes in the club's structure. He reorganised the institution's economy, making it the richest club in the world, and made far-reaching changes at the top of the organisation. He completely renovated the Santiago Bernabéu, created a new sports complex in Valdebebas and opened the Alfredo Di Stéfano stadium. Meanwhile, on the pitch, he made the fans' dreams come true by bringing in Zidane, Ronaldo and Beckham.</p>
          <p>n his second spell (2006), the president continued to delight the supporters, signing the best players and managers in the world. Great players such as Cristiano Ronaldo and Benzemá among others, were brought in, along with manager José Mourinho. The Portuguese arrived in the Santiago Bernabéu a week after being crowned champions of Europe with Inter Milan in the same stadium. </p>
          <hr>
          <h2 class="font-weight-bold text-primary text-center">1991-2000</h2>
          <p>Having demonstrated his abilities at the helm of Tenerife, where his team played an attractive and efficient brand of football, Valdano returned to Real Madrid in 1994. With new signings Redondo, Laudrup, Amavisca and Cañizares, the Madrid side went on to win the league title. That same season, youth-academy player Raúl made his debut. On the 29th of October at 17 years of age, the young player from Madrid filled in for Martín Vázquez in La Romareda, where he would put in a stunning performance. A new legend was born.</p>
          <p>Early in 1995, Valdano's Real Madrid beat Johan Cruyff's Barça 5-0 in the Santiago Bernabéu. It was a magical game that was televised and followed by more than 10 million viewers. But the bad results in the 95-96 season forced Lorenzo Sanz to bring in Fabio Capello, one of the most sought-after coaches in European football. The Italian had a dream squad. The signings of Seedorf, Suker, Mijatovic and Roberto Carlos, together with Raúl, Hierro and Redondo, took Madrid to a new league title.</p>
          <p>The 20th of May 1998 was a historic day for the club. After 32 years, and under the orders of Jupp Heynckes, Real Madrid conquered Europe once more by beating Juventus in the final of the Champions League. A goal from Pedja Mijatovic in the 66th minute brought number Seven from the Amsterdam Arena to the Santiago Bernabéu trophy room. In December that year, this time at the hands of Guus Hiddink, Madrid won its second Intercontinental Cup.</p>
          <p>In 1999, and after a lifetime connected to the club as a player, Vicente del Bosque returned as the first-team manager. The man from Salamanca managed to instil a philosophy in the team that made them the best in the continent. His first title came in 2000: the Eighth European Cup. In the same year, Florentino Pérez (enlazar ficha) took over the presidency and signed one of the best players on the planet, Luis Figo.</p>
          <hr>
          <h2 class="font-weight-bold text-primary text-center">1981-1990</h2>
          <p>In 1983, Castilla was crowned champion of the Segunda División under the orders of Amancio and with some stunning performances from five players: Pardeza, Sanchís, Míchel, Martín Vázquez and Butragueño. These gems from the academy were a real discovery and Di Stéfano did not hesitate to prepare them for the first team. The group made its breakthrough in 1985, winning five consecutive La Ligas and setting important records, such as the competition's top goal-scorer with 107.</p>
          <p>Mexican striker Hugo Sánchez had a lot to do with this success. Together with veterans Juanito, Valdano and Santillana, he formed a 'Cohort' that was close to perfection. In his seven seasons in white he scored 251 goals, and was the league's top goal-scorer in four of them. His famous front-flip celebrations are burned into the retinas of Madrid fans.</p>
          <p>In this decade Real Madrid also won its first UEFA title. It came in the 1984-85 season, in a two-legged final where they beat Videoton, a little-known team who had knocked out PSG, Partizán Belgrade and Manchester United. In the following campaign, the Whites successfully defended their title thanks to an unbelievable comeback. After losing the first leg 5-1 to Borussia Mönchengladbach, they won an epic tie in the return match with two goals from Valdano and another brace from Santillana to reach the quarters (4-0). </p>
        </div>
      </div>
    </div>
    
  </main>